-- MySQL Script generated by MySQL Workbench
-- 02/28/16 23:47:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema recruitment_tool_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema recruitment_tool_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recruitment_tool_db` DEFAULT CHARACTER SET utf8 ;
USE `recruitment_tool_db` ;

-- -----------------------------------------------------
-- Table `recruitment_tool_db`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recruitment_tool_db`.`role` ;

CREATE TABLE IF NOT EXISTS `recruitment_tool_db`.`role` (
  `role_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `authority_name` VARCHAR(255) NOT NULL,
  `public` INT(1) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `authority_name_UNIQUE` (`authority_name` ASC));


-- -----------------------------------------------------
-- Table `recruitment_tool_db`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recruitment_tool_db`.`person` ;

CREATE TABLE IF NOT EXISTS `recruitment_tool_db`.`person` (
  `person_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `surname` VARCHAR(255) NULL DEFAULT NULL,
  `ssn` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `enabled` INT(1) NOT NULL DEFAULT 1,
  `role_id` BIGINT NOT NULL,
  PRIMARY KEY (`person_id`),
  INDEX `role_fk_idx` (`role_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_role_person`
    FOREIGN KEY (`role_id`)
    REFERENCES `recruitment_tool_db`.`role` (`role_id`));


-- -----------------------------------------------------
-- Table `recruitment_tool_db`.`availability`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recruitment_tool_db`.`availability` ;

CREATE TABLE IF NOT EXISTS `recruitment_tool_db`.`availability` (
  `availability_id` BIGINT NOT NULL AUTO_INCREMENT,
  `person_id` BIGINT NOT NULL,
  `from_date` DATE NULL DEFAULT NULL,
  `to_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`availability_id`),
  INDEX `fk_person_idx_2` (`person_id` ASC),
  CONSTRAINT `fk_person_availability`
    FOREIGN KEY (`person_id`)
    REFERENCES `recruitment_tool_db`.`person` (`person_id`));


-- -----------------------------------------------------
-- Table `recruitment_tool_db`.`competence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recruitment_tool_db`.`competence` ;

CREATE TABLE IF NOT EXISTS `recruitment_tool_db`.`competence` (
  `competence_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`competence_id`));


-- -----------------------------------------------------
-- Table `recruitment_tool_db`.`competence_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recruitment_tool_db`.`competence_profile` ;

CREATE TABLE IF NOT EXISTS `recruitment_tool_db`.`competence_profile` (
  `competence_profile_id` BIGINT NOT NULL,
  `person_id` BIGINT NOT NULL,
  `competence_id` BIGINT NOT NULL,
  `years_of_experience` DECIMAL(4,2) NULL DEFAULT NULL,
  PRIMARY KEY (`competence_profile_id`),
  INDEX `_idx` (`person_id` ASC),
  INDEX `fk_competence_idx` (`competence_id` ASC),
  CONSTRAINT `fk_person_competence_profile`
    FOREIGN KEY (`person_id`)
    REFERENCES `recruitment_tool_db`.`person` (`person_id`),
  CONSTRAINT `fk_competence_competence_profile`
    FOREIGN KEY (`competence_id`)
    REFERENCES `recruitment_tool_db`.`competence` (`competence_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



show databases;

use recruitment_tool_db;

show tables;

INSERT INTO role (name, authority_name, public) VALUES ('recruit', 'ROLE_RECRUIT', 1);
INSERT INTO role (name, authority_name, public) VALUES ('applicant', 'ROLE_APPLICANT', 1);
INSERT INTO role (name, authority_name, public) VALUES ('admin', 'ROLE_ADMIN', 0);

INSERT INTO person (name, surname, username, password, role_id)
VALUES ('Greta', 'Borg', 'borg', 'wl9nk23a', 1);
INSERT INTO person (name, surname, ssn, email, role_id)
VALUES ('Per', 'Strand', '19671212-1211', 'per@strand.kth.se', 2);

INSERT INTO availability (person_id, from_date, to_date)
VALUES (2, '2014-02-23', '2014-05-25');
INSERT INTO availability (person_id, from_date, to_date)
VALUES (2, '2014-07-10', '2014-08-10');
INSERT INTO competence (name)
VALUES ('Korvgrillning');
INSERT INTO competence (name)
VALUES ('Karuselldrift');
INSERT INTO competence_profile (competence_profile_id, person_id,
competence_id, years_of_experience)
VALUES (1, 2, 1, 3.5);
INSERT INTO competence_profile (competence_profile_id, person_id,
competence_id, years_of_experience)
VALUES (2, 2, 2, 2.0);


select * from person;

select * from role;



SELECT u.username, r.authority_name FROM Person u, Role r WHERE u.role_id = r.role_id AND u.username="borg";

SELECT username, password, CASE enabled WHEN 1 THEN 'true' ELSE 'false' END 'enabled' FROM Person WHERE username="borg";
